# Test suite must pass on Travis before merging into `master`.
status = [
    "continuous-integration/travis-ci/push",
]

# This feature is rarely useful and more often problematic, so we turn it off.
delete_merged_branches = false
